import daisyui from 'daisyui'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#d3bbff",
        "tertiary-fixed": "#e3e1ed",
        "surface-container-highest": "#d5e3fc",
        "on-tertiary-fixed": "#1a1b23",
        "on-tertiary-container": "#cfcdd9",
        "outline": "#7b7486",
        "outline-variant": "#ccc3d7",
        "background": "#f8f9ff",
        "on-surface-variant": "#4a4455",
        "on-secondary-fixed": "#1b1a29",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "primary-fixed": "#ebddff",
        "secondary": "#5e5c6e",
        "on-primary-container": "#dac5ff",
        "on-error": "#ffffff",
        "tertiary": "#3f4049",
        "surface-variant": "#d5e3fc",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#464555",
        "tertiary-container": "#575761",
        "primary": "#5300b7",
        "inverse-surface": "#233144",
        "on-background": "#0d1c2e",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed": "#250059",
        "surface-tint": "#7331df",
        "secondary-fixed-dim": "#c7c4d8",
        "primary-container": "#6d28d9",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container": "#e6eeff",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-container": "#646274",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#e4e0f5",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c7c5d1",
        "secondary-container": "#e4e0f5",
        "inverse-primary": "#d3bbff",
        "surface-dim": "#ccdbf3",
        "on-surface": "#0d1c2e",
        "on-primary-fixed-variant": "#5b00c5",
        "surface": "#f8f9ff",
        "on-tertiary-fixed-variant": "#46464f",
        "blue-business-accent": "#dbeafe",
        "blue-business-primary": "#1e69dc",
        "violet-bloom-primary": "#7033ff",
        "violet-bloom-accent": "#e2ebff",
        "green-fast-accent": "#dcfce7",
        "green-fast-primary": "#4ac885",
        "status-success": "#009668",
        "status-warning": "#f59e0b",
        "status-danger": "#ba1a1a",
        "status-info": "#0058be",
        "warning-container": "#fef3c7",
        "amber-100": "#fef3c7"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        card: "28px"
      },
      spacing: {
        "sidebar-expanded": "260px",
        "stack-sm": "8px",
        "container-padding": "32px",
        "gutter": "24px",
        "sidebar-collapsed": "80px",
        "stack-md": "16px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "base-unit": "4px",
        "container-margin": "24px"
      },
      fontFamily: {
        kantumruy: ["Kantumruy Pro", "serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-base": ["Hanken Grotesk", "sans-serif"],
        "data-tabular": ["Hanken Grotesk", "sans-serif"],
        "title-sm": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [daisyui],
}