const express = require("express")
const restrict = require("../guards/restrict.guard")
const controller = require("../controller/admin-manager.controller")

const router = express.Router()

router.use(restrict("ADMIN_MANAGER"))

router.get("/dashboard", controller.dashboard)
router.route("/shops")
    .get(controller.listShops)
    .post(controller.createShop)
router.route("/shops/:id")
    .get(controller.getShop)
    .patch(controller.updateShop)
    .delete(controller.deleteShop)
router.patch("/shops/:id/status", controller.updateShopStatus)
router.patch("/shops/:id/archive", controller.archiveShop)
router.patch("/shops/:id/restore", controller.restoreShop)
router.route("/admins")
    .get(controller.listAdmins)
    .post(controller.createAdmin)
router.route("/admins/:id")
    .get(controller.getAdmin)
    .patch(controller.updateAdmin)
router.patch("/admins/:id/status", controller.updateAdminStatus)
router.get("/reports", controller.platformReports)
router.get("/audit-logs", controller.auditLogs)
router.get("/alerts", controller.alerts)
router.get("/system-health", controller.systemHealth)
router.get("/products", controller.getProducts)
router.get("/products/:id", controller.getProduct)
router.route("/backups")
    .get(controller.listBackups)
    .post(controller.createBackup)
router.delete("/backups/:id", controller.deleteBackup)
router.get("/backups/:id/download", controller.downloadBackup)

router.get("/notifications", controller.getNotifications)
router.get("/notifications/unread-count", controller.getUnreadCount)
router.patch("/notifications/read-all", controller.markAllAsRead)
router.patch("/notifications/:id/read", controller.markAsRead)

module.exports = router
