upstream kambuja_pos_api {
    server 127.0.0.1:8080;
}

upstream kambuja_pos_manager {
    server 127.0.0.1:5173;
}

upstream kambuja_pos_shop {
    server 127.0.0.1:5174;
}

server {
    listen 80;
    server_name manager.example.com;

    location /api/ {
        proxy_pass http://kambuja_pos_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://kambuja_pos_manager;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 80;
    server_name pos.example.com;

    location /api/ {
        proxy_pass http://kambuja_pos_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://kambuja_pos_shop;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
