export const endpoints = {
  login: "/auth/login",
  adminDashboard: "/admin/dashboard",
  shop: "/admin/shop",
  products: "/products",
  productCodes: "/product-codes",
  categories: "/categories",
  inventory: "/inventory",
  stockMovements: "/stock-movements",
  cashiers: "/cashiers",
  createCashier: "/admin/cashiers",
  sales: "/sales",
  payments: "/payments",
  receipts: "/receipts",
  customers: "/customers",
  reports: "/reports",
  notifications: "/notifications",
  settings: "/settings",
  telegram: "/telegram",
};
