// Cambodia administrative divisions — 25 province-level + all districts
const d=(code,nameKh,nameEn,typeKh,typeEn,provinceCode)=>({code,nameKh,nameEn,typeKh,typeEn,provinceCode});
const p=(code,nameKh,nameEn,typeKh,typeEn,districts)=>({code,nameKh,nameEn,typeKh,typeEn,districts});

export const CAMBODIA_PROVINCES=[
p("PP","រាជធានីភ្នំពេញ","Phnom Penh","រាជធានី","Capital",[
  d("PP01","ចំការមន","Chamkarmon","ខណ្ឌ","Khan","PP"),
  d("PP02","ដូនពេញ","Daun Penh","ខណ្ឌ","Khan","PP"),
  d("PP03","៧មករា","7 Makara","ខណ្ឌ","Khan","PP"),
  d("PP04","ទួលគោក","Tuol Kouk","ខណ្ឌ","Khan","PP"),
  d("PP05","ដង្កោ","Dangkao","ខណ្ឌ","Khan","PP"),
  d("PP06","មានជ័យ","Mean Chey","ខណ្ឌ","Khan","PP"),
  d("PP07","រុស្ស៊ីកែវ","Russey Keo","ខណ្ឌ","Khan","PP"),
  d("PP08","សែនសុខ","Sen Sok","ខណ្ឌ","Khan","PP"),
  d("PP09","ពោធ៍សែនជ័យ","Por Sen Chey","ខណ្ឌ","Khan","PP"),
  d("PP10","ជ្រោយចង្វារ","Chroy Changvar","ខណ្ឌ","Khan","PP"),
  d("PP11","ព្រែកព្នៅ","Prek Pnov","ខណ្ឌ","Khan","PP"),
  d("PP12","ច្បារអំពៅ","Chbar Ampov","ខណ្ឌ","Khan","PP"),
  d("PP13","បឹងកេងកាង","Boeng Keng Kang","ខណ្ឌ","Khan","PP"),
  d("PP14","កំបូល","Kamboul","ខណ្ឌ","Khan","PP"),
]),
p("01","បន្ទាយមានជ័យ","Banteay Meanchey","ខេត្ត","Province",[
  d("0101","មង្គលបូរី","Mongkol Borei","ស្រុក","District","01"),
  d("0102","ព្រះនេត្រព្រះ","Preah Netr Preah","ស្រុក","District","01"),
  d("0103","អូរជ្រៅ","Ou Chrov","ស្រុក","District","01"),
  d("0104","សិរីសោភ័ណ","Serei Saophoan","ស្រុក","District","01"),
  d("0105","មន្ទីរ","Malai","ស្រុក","District","01"),
  d("0106","ថ្មពួក","Thma Puok","ស្រុក","District","01"),
  d("0107","ស្វាយជ្រំ","Svay Chek","ស្រុក","District","01"),
  d("0108","ប៉ោយប៉ែត","Paoy Paet","ស្រុក","District","01"),
  d("0109","ភ្នំស្រុក","Phnum Srok","ស្រុក","District","01"),
]),
p("02","បាត់ដំបង","Battambang","ខេត្ត","Province",[
  d("0201","បាត់ដំបង","Battambang","ស្រុក","District","02"),
  d("0202","បាណន់","Banan","ស្រុក","District","02"),
  d("0203","មោងរឹស្សី","Moung Ruessei","ស្រុក","District","02"),
  d("0204","ភ្នំព្រឹក","Phnum Proek","ស្រុក","District","02"),
  d("0205","រតនៈមណ្ឌល","Rotanak Mondol","ស្រុក","District","02"),
  d("0206","សំឡូត","Samlout","ស្រុក","District","02"),
  d("0207","សង្កែ","Sangker","ស្រុក","District","02"),
  d("0208","សំពៅលូន","Sampov Lun","ស្រុក","District","02"),
  d("0209","ថ្មគោល","Thma Koul","ស្រុក","District","02"),
  d("0210","កំរៀង","Kamrieng","ស្រុក","District","02"),
  d("0211","កោះក្រឡោ","Koa Krolar","ស្រុក","District","02"),
  d("0212","រូហ្ករ","Rukhak Kiri","ស្រុក","District","02"),
]),
p("03","កំពង់ចាម","Kampong Cham","ខេត្ត","Province",[
  d("0301","កំពង់ចាម","Kampong Cham","ស្រុក","District","03"),
  d("0302","បាធាយ","Batheay","ស្រុក","District","03"),
  d("0303","ចំការលើ","Chamkar Leu","ស្រុក","District","03"),
  d("0304","ជើងព្រៃ","Cheung Prey","ស្រុក","District","03"),
  d("0305","ដំបែ","Dambae","ស្រុក","District","03"),
  d("0306","កំពង់សៀម","Kampong Siem","ស្រុក","District","03"),
  d("0307","កាំងមាស","Kang Meas","ស្រុក","District","03"),
  d("0308","កោះសូទិន","Koh Sotin","ស្រុក","District","03"),
  d("0309","ពញាក្រែក","Ponhea Kraek","ស្រុក","District","03"),
  d("0310","ព្រៃឈរ","Prey Chhor","ស្រុក","District","03"),
  d("0311","ស្រីសន្ធរ","Srey Santhor","ស្រុក","District","03"),
  d("0312","ស្ទឹងត្រង់","Stueng Trang","ស្រុក","District","03"),
]),
p("04","កំពង់ឆ្នាំង","Kampong Chhnang","ខេត្ត","Province",[
  d("0401","កំពង់ឆ្នាំង","Kampong Chhnang","ស្រុក","District","04"),
  d("0402","បរិបូរណ៍","Baribour","ស្រុក","District","04"),
  d("0403","ជ័យគីរី","Chol Kiri","ស្រុក","District","04"),
  d("0404","កំពង់លាង","Kampong Leaeng","ស្រុក","District","04"),
  d("0405","កំពង់ត្រឡាច","Kampong Tralach","ស្រុក","District","04"),
  d("0406","ភ្នំក្រវាញ","Phnum Kravanh","ស្រុក","District","04"),
  d("0407","រលៀបៀ","Rolea B'ier","ស្រុក","District","04"),
  d("0408","សាមគ្គីមានជ័យ","Samaki Mean Chey","ស្រុក","District","04"),
  d("0409","ទឹកផុស","Tuek Phos","ស្រុក","District","04"),
]),
p("05","កំពង់ស្ពឺ","Kampong Speu","ខេត្ត","Province",[
  d("0501","ច្បារមន","Chbar Mon","ស្រុក","District","05"),
  d("0502","ឱរ៉ាល់","Aoral","ស្រុក","District","05"),
  d("0503","បសេដ្ឋ","Basedth","ស្រុក","District","05"),
  d("0504","កងពិសី","Kong Pisei","ស្រុក","District","05"),
  d("0505","ភ្នំស្រួច","Phnum Sruoch","ស្រុក","District","05"),
  d("0506","សំរោងទង","Samraong Tong","ស្រុក","District","05"),
  d("0507","ថ្ពង","Thpong","ស្រុក","District","05"),
]),
p("06","កំពង់ធំ","Kampong Thom","ខេត្ត","Province",[
  d("0601","ស្ទឹងសែន","Stueng Saen","ស្រុក","District","06"),
  d("0602","បារាយណ៍","Baray","ស្រុក","District","06"),
  d("0603","កំពង់ស្វាយ","Kampong Svay","ស្រុក","District","06"),
  d("0604","ប្រាសាទបល្ល័ង្ក","Prasat Ballangk","ស្រុក","District","06"),
  d("0605","ប្រាសាទសំបូរ","Prasat Sambour","ស្រុក","District","06"),
  d("0606","សណ្ដាន់","Sandann","ស្រុក","District","06"),
  d("0607","សន្តុក","Santuk","ស្រុក","District","06"),
]),
p("07","កំពត","Kampot","ខេត្ត","Province",[
  d("0701","កំពត","Kampot","ស្រុក","District","07"),
  d("0702","អង្គរជ័យ","Angkor Chey","ស្រុក","District","07"),
  d("0703","បន្ទាយមាស","Banteay Meas","ស្រុក","District","07"),
  d("0704","ឈូក","Chhuk","ស្រុក","District","07"),
  d("0705","ជំនរគីរី","Chum Kiri","ស្រុក","District","07"),
  d("0706","ដង់តុង","Dang Tong","ស្រុក","District","07"),
  d("0707","កំពង់ត្រាច","Kampong Trach","ស្រុក","District","07"),
  d("0708","ទឹកឈូ","Tuek Chhou","ស្រុក","District","07"),
]),
p("08","កណ្ដាល","Kandal","ខេត្ត","Province",[
  d("0801","ស្អាង","Sa'ang","ស្រុក","District","08"),
  d("0802","អង្កស្នួល","Angk Snuol","ស្រុក","District","08"),
  d("0803","កៀនស្វាយ","Kien Svay","ស្រុក","District","08"),
  d("0804","ខ្សាច់កណ្ដាល","Khsach Kandal","ស្រុក","District","08"),
  d("0805","ល្បើក","Lbaeuk","ស្រុក","District","08"),
  d("0806","លើកដែក","Leuk Daek","ស្រុក","District","08"),
  d("0807","ល្វាឯម","Lovea Em","ស្រុក","District","08"),
  d("0808","មុខកំពូល","Muk Kampul","ស្រុក","District","08"),
  d("0809","ពញាលើ","Ponhea Lueu","ស្រុក","District","08"),
  d("0810","រកាខ្ពស់","Rokar Khpos","ស្រុក","District","08"),
  d("0811","តាខ្មៅ","Takhmao","ស្រុក","District","08"),
]),
p("09","កែប","Kep","ខេត្ត","Province",[
  d("0901","កែប","Kep","ស្រុក","District","09"),
  d("0902","ដំណាក់ចង្អែរ","Damnak Chang'aeur","ស្រុក","District","09"),
]),
p("10","កោះកុង","Koh Kong","ខេត្ត","Province",[
  d("1001","កោះកុង","Koh Kong","ស្រុក","District","10"),
  d("1002","បទុំស្គរ","Botum Sakor","ស្រុក","District","10"),
  d("1003","គីរីស្គរ","Kiri Sakor","ស្រុក","District","10"),
  d("1004","មណ្ឌលសីម៉ា","Mondul Seima","ស្រុក","District","10"),
  d("1005","ស្មាចមានជ័យ","Smach Mean Chey","ស្រុក","District","10"),
  d("1006","ស្រែអំបិល","Sre Ambel","ស្រុក","District","10"),
  d("1007","ថ្មបាំង","Thma Bang","ស្រុក","District","10"),
]),
p("11","ក្រចេះ","Kratie","ខេត្ត","Province",[
  d("1101","ក្រចេះ","Kratie","ស្រុក","District","11"),
  d("1102","ឈ្លុង","Chhlong","ស្រុក","District","11"),
  d("1103","កំពង់ត្រាច","Kampong Trach","ស្រុក","District","11"),
  d("1104","ភ្នំក្រកោ","Phnum Krakor","ស្រុក","District","11"),
  d("1105","សំបូរ","Sambour","ស្រុក","District","11"),
  d("1106","ស្នួល","Snuol","ស្រុក","District","11"),
]),
p("12","មណ្ឌលគីរី","Mondulkiri","ខេត្ត","Province",[
  d("1201","សែនមនោរម្យ","Senmonorom","ស្រុក","District","12"),
  d("1202","កែវសីម៉ា","Kaev Seima","ស្រុក","District","12"),
  d("1203","កោះញែក","Koh Nhek","ស្រុក","District","12"),
  d("1204","អូរ៉ែន","O'Raing","ស្រុក","District","12"),
  d("1205","ពេជ្រជ្រាដ","Pech Chreada","ស្រុក","District","12"),
]),
p("13","ឧត្តរមានជ័យ","Oddar Meanchey","ខេត្ត","Province",[
  d("1301","សំរោង","Samraong","ស្រុក","District","13"),
  d("1302","អន្លង់វែង","Anlong Veng","ស្រុក","District","13"),
  d("1303","បន្ទាយអំពិល","Banteay Ampil","ស្រុក","District","13"),
  d("1304","ជងកាល់","Chong Kal","ស្រុក","District","13"),
  d("1305","ត្រពាំងប្រសាទ","Trapeang Prasat","ស្រុក","District","13"),
]),
p("14","ប៉ៃលិន","Pailin","ខេត្ត","Province",[
  d("1401","ប៉ៃលិន","Pailin","ស្រុក","District","14"),
  d("1402","សាលាក្រៅ","Sala Krau","ស្រុក","District","14"),
]),
p("15","ព្រះសីហនុ","Preah Sihanouk","ខេត្ត","Province",[
  d("1501","ព្រះសីហនុ","Sihanoukville","ស្រុក","District","15"),
  d("1502","កំពង់សីឡា","Kampong Seila","ស្រុក","District","15"),
  d("1503","ព្រៃនប់","Prey Nob","ស្រុក","District","15"),
  d("1504","ស្ទឹងហាវ","Stueng Hav","ស្រុក","District","15"),
]),
p("16","ព្រះវិហារ","Preah Vihear","ខេត្ត","Province",[
  d("1601","ត្បែងមានជ័យ","Tbeng Meanchey","ស្រុក","District","16"),
  d("1602","ឆែប","Chhaeb","ស្រុក","District","16"),
  d("1603","ជាំខ្ស័ន្ត","Choam Khsant","ស្រុក","District","16"),
  d("1604","គូលែន","Kulen","ស្រុក","District","16"),
  d("1605","រវៀង","Rovieng","ស្រុក","District","16"),
  d("1606","សង្គមថ្មី","Sangkom Thmey","ស្រុក","District","16"),
]),
p("17","ព្រៃវែង","Prey Veng","ខេត្ត","Province",[
  d("1701","ព្រៃវែង","Prey Veng","ស្រុក","District","17"),
  d("1702","បាភ្នំ","Ba Phnum","ស្រុក","District","17"),
  d("1703","កំចាយមារ","Kamchay Mear","ស្រុក","District","17"),
  d("1704","កំពង់ត្របែក","Kampong Trabaek","ស្រុក","District","17"),
  d("1705","កញ្ជ្រៀច","Kanhchriech","ស្រុក","District","17"),
  d("1706","មេសង","Me Sang","ស្រុក","District","17"),
  d("1707","ពាមជរ","Peam Chor","ស្រុក","District","17"),
  d("1708","ពារៀង","Pea Reang","ស្រុក","District","17"),
  d("1709","ព្រះស្ដេច","Preah Sdach","ស្រុក","District","17"),
  d("1710","ពរ រៀង","Pur Rieng","ស្រុក","District","17"),
  d("1711","សិទ្ធិខណ្ឌ","Sithor Kandal","ស្រុក","District","17"),
]),
p("18","ពោធ៍សាត់","Pursat","ខេត្ត","Province",[
  d("1801","ពោធ៍សាត់","Pursat","ស្រុក","District","18"),
  d("1802","បាកាន","Bakan","ស្រុក","District","18"),
  d("1803","កណ្ដៀង","Kandieng","ស្រុក","District","18"),
  d("1804","ក្រគរ","Krakor","ស្រុក","District","18"),
  d("1805","ភ្នំក្រវាញ","Phnum Kravanh","ស្រុក","District","18"),
  d("1806","វាលវែង","Veal Veaeng","ស្រុក","District","18"),
]),
p("19","រតនគីរី","Ratanakiri","ខេត្ត","Province",[
  d("1901","បានលុង","Banlung","ស្រុក","District","19"),
  d("1902","អណ្ដូងមាស","Andong Meas","ស្រុក","District","19"),
  d("1903","បរ ក្ែវ","Bar Kaev","ស្រុក","District","19"),
  d("1904","កូនមម","Koun Mom","ស្រុក","District","19"),
  d("1905","លំផាត់","Lumphat","ស្រុក","District","19"),
  d("1906","អូរឈូម","O'Chum","ស្រុក","District","19"),
  d("1907","អូរយ៉ាដាវ","O'Yadav","ស្រុក","District","19"),
  d("1908","ផ្ដើង","Padng","ស្រុក","District","19"),
  d("1909","វើនសៃ","Voen Sai","ស្រុក","District","19"),
]),
p("20","សៀមរាប","Siem Reap","ខេត្ត","Province",[
  d("2001","សៀមរាប","Siem Reap","ស្រុក","District","20"),
  d("2002","អង្គរជុំ","Angkor Chum","ស្រុក","District","20"),
  d("2003","អង្គរធំ","Angkor Thom","ស្រុក","District","20"),
  d("2004","បន្ទាយស្រី","Banteay Srei","ស្រុក","District","20"),
  d("2005","ជីក្រែង","Chi Kraeng","ស្រុក","District","20"),
  d("2006","ក្រឡាញ់","Kralanh","ស្រុក","District","20"),
  d("2007","ប្រាសាទបាគង","Prasat Bakong","ស្រុក","District","20"),
  d("2008","ពួក","Puok","ស្រុក","District","20"),
  d("2009","សូទ្និគម","Sotnikum","ស្រុក","District","20"),
  d("2010","ស្រីស្នំ","Srei Snam","ស្រុក","District","20"),
  d("2011","ស្វាយលើ","Svay Leu","ស្រុក","District","20"),
  d("2012","វ៉ារិន","Varin","ស្រុក","District","20"),
]),
p("21","ស្ទឹងត្រែង","Stung Treng","ខេត្ត","Province",[
  d("2101","ស្ទឹងត្រែង","Stung Treng","ស្រុក","District","21"),
  d("2102","សៀមបូក","Siem Bouk","ស្រុក","District","21"),
  d("2103","សៀមប៉ាង","Siem Pang","ស្រុក","District","21"),
  d("2104","ថាឡាបរិវ៉ាត","Thala Barivat","ស្រុក","District","21"),
  d("2105","សេសាន","Sesan","ស្រុក","District","21"),
]),
p("22","ស្វាយរៀង","Svay Rieng","ខេត្ត","Province",[
  d("2201","ស្វាយរៀង","Svay Rieng","ស្រុក","District","22"),
  d("2202","ច័ន្ទ្រា","Chantrea","ស្រុក","District","22"),
  d("2203","កំពង់រោ","Kampong Rou","ស្រុក","District","22"),
  d("2204","រមាសហែក","Romeas Haek","ស្រុក","District","22"),
  d("2205","ស្វាយជ្រំ","Svay Chrum","ស្រុក","District","22"),
  d("2206","ស្វាយទាប","Svay Teab","ស្រុក","District","22"),
]),
p("23","តាកែវ","Takeo","ខេត្ត","Province",[
  d("2301","ដូនកែវ","Doun Kaev","ស្រុក","District","23"),
  d("2302","អង្គរបុរី","Angkor Borei","ស្រុក","District","23"),
  d("2303","បាទី","Bati","ស្រុក","District","23"),
  d("2304","បូរីជលស្ថរ","Borei Cholsar","ស្រុក","District","23"),
  d("2305","កោះអណ្ដែត","Kaoh Andaet","ស្រុក","District","23"),
  d("2306","គីរីវ៉ង","Kirivoung","ស្រុក","District","23"),
  d("2307","ព្រៃកប្បាស","Prey Kabbas","ស្រុក","District","23"),
  d("2308","សំរោង","Samraong","ស្រុក","District","23"),
  d("2309","ត្រាំកក់","Tram Kak","ស្រុក","District","23"),
  d("2310","ទ្រាំង","Treang","ស្រុក","District","23"),
]),
p("24","ត្បូងឃ្មុំ","Tboung Khmum","ខេត្ត","Province",[
  d("2401","សួង","Suong","ស្រុក","District","24"),
  d("2402","ដំបែ","Dambe","ស្រុក","District","24"),
  d("2403","ក្រូចឆ្មារ","Krouch Chhmar","ស្រុក","District","24"),
  d("2404","មេម៉ូត","Memut","ស្រុក","District","24"),
  d("2405","អូររាំងអូ","Ou Reang Ov","ស្រុក","District","24"),
  d("2406","ពញាក្រែក","Ponhea Kraek","ស្រុក","District","24"),
  d("2407","ត្បូងឃ្មុំ","Tboung Khmum","ស្រុក","District","24"),
]),
];

export function getDistrictsForProvince(provinceCode){
  if(!provinceCode)return[];
  const prov=CAMBODIA_PROVINCES.find(p=>p.code===provinceCode);
  return prov?prov.districts:[];
}

// Legacy helper — kept for backward compat
export function locationOptions(shops){
  const provinces=[...new Set(shops.map(s=>s.province).filter(Boolean))].sort();
  const cities=[...new Set(shops.map(s=>s.city).filter(Boolean))].sort();
  return{provinces,cities};
}
